### ISSUE TITLE
(询问)请问您对于网上这些倒卖程序是什么看法

### ISSUE THREAD

**Issue by hshx123** [StageGuard/SkyAutoPlayerScript#1]
刚才我在哔哩哔哩搜索 **光遇乐谱**，查看专栏时，似乎发现了您的脚本  
[专栏地址](https://www.bilibili.com/read/cv5938490) 。
    
我想您肯定知道您的脚本会被倒卖，请问您对这件事有什么看法？(如果不想回答的话也没有关系)

**Comment by StageGuard** [comment]
当从非法途径购买到`SkyAutoPlayerScript`的人首次使用时看到了开源提示，我想他们已经知道自己被骗了，我相信他们肯定有举报的自觉性。
<u>**坏人永远会有，但同样好人远比坏人多。**</u>

我很高兴我的脚本能被认可，我在芥子空间也看到有人发我的脚本，他明确标注了作者和来源。
我也很气愤有人未经我的允许使用我的脚本用作盈利用途但**没有标注来源**(受限于`GPLv3`)。
(我并没有考察那个倒卖我脚本的人是否标注脚本来源，但我猜测他一定没有标注，或者通过一定手段去掉了关于脚本来源的所有信息，否则他是不可能获利的。)

**但由于`SkyAutoPlayerScript`是开源的，所有人都有权力修改代码，所以我没有任何手段和能力制止他们。**
**能制止他们的只有他们的自觉性**。
我很早就听许多前辈说过一句话：**软件协议终究只是君子的软件协议**，这在中国非常明显。

这个项目永远也不会闭源，用户上传的乐谱也永远不会加密，我会继续修复脚本的Bug并更新新的内容。
这一切最终的受害者是那些被蒙在鼓里的付费的人。
如果他们觉得他们愿意恰烂钱并且恰得安心，那就随他们去吧。

由于我大多在酷安发布`SkyAutoPlayerScript`新版本动态，其他平台关于`SkyAutoPlayerScript`的情况我一无所知，所以感谢你告诉我这件事情！

**Comment by StageGuard** [comment]
不关闭issue了，让更多人看到
