### ISSUE TITLE
運行不了 自動彈奏

### ISSUE THREAD

**Issue by MatthewCz13** [StageGuard/SkyAutoPlayerScript#18]
![Screenshot_2022-02-21-17-51-16-866_org autojs autojs](https://user-images.githubusercontent.com/100126655/154930634-2ec32fac-2730-4bd1-80ea-def8edbe717d.jpg)
點擊運行後就變成空白了 請問是什麼問題

**Comment by MatthewCz13** [comment]
客服在嗎可以幫忙看一下什麼問題嗎

**Comment by StageGuard** [comment]
https://github.com/StageGuard/SkyAutoPlayerScript/issues/17#issuecomment-1002640892

**Comment by MatthewCz13** [comment]
> 

具體怎麼操作

**Comment by MatthewCz13** [comment]
不好意思麻煩你了 我有點看不明白 那個要怎麼操作



StageGuard ***@***.***> 於 2022年2月22日 週二 下午5:11 寫道：
