### ISSUE TITLE
[Feature request] 添加随机停顿与随机错误

### ISSUE THREAD

**Issue by tiaod** [StageGuard/SkyAutoPlayerScript#2]
脚本目前演奏乐谱的速度非常均匀、流畅，且100%正确，缺少手弹的那种停顿感，听起来没有灵魂，一听就知道是脚本。建议新增一个选项，启用后会随机地插入停顿，并且会随机弹错相邻的按键，让脚本演奏更有灵魂。作者看看这个想法如何？如果OK的话我周末写个PR

**Comment by StageGuard** [comment]
这个feature未来将会被加入。

**Comment by StageGuard** [comment]
@tiaod 你要pr吗，你pr的话我就不写了（

**Comment by tiaod** [comment]
😂我得过段时间，最近忙其他项目

**Comment by StageGuard** [comment]
(滑稽)

**Comment by tiaod** [comment]
随机错误我尝试写过，效果不太好，还是没有手弹的感觉。所以我感觉吧，模拟手弹这一步应该交给乐谱去完成，有这个需求的直接编辑乐谱，手动修改出一些错误和停顿。甚至忘词倒带的效果，都能通过修改乐谱实现。而脚本只需要实现准确演奏乐谱。
