### ISSUE TITLE
下版本优化建议

### ISSUE THREAD

**Issue by nymanyim** [StageGuard/SkyAutoPlayerScript#22]
大大，下个版本谱子目录可以考虑识别文件夹嘛，这样方便分类了(*^▽^*)

**Comment by StageGuard** [comment]
没有必要

**Comment by nymanyim** [comment]
歌曲多了的话，区分不同类型的音乐很难
另外，可以考虑添加一个移除无效歌曲按钮嘛🤣

**Comment by StageGuard** [comment]
> 歌曲多了的话，区分不同类型的音乐很难 另外，可以考虑添加一个移除无效歌曲按钮嘛🤣

长按删除

**Comment by nymanyim** [comment]
> > 歌曲多了的话，区分不同类型的音乐很难 另外，可以考虑添加一个移除无效歌曲按钮嘛🤣
> 
> 长按删除

说错了，应该是一键移除无效歌曲。这样的话就更好了🤣
