### ISSUE TITLE
第二次启用异常

### ISSUE THREAD

**Issue by qiuyueovo** [StageGuard/SkyAutoPlayerScript#35]
我是直接进入到 https://cdn.jsdelivr.net/gh/StageGuard/SkyAutoPlayerScript/source/SkyAutoplayer.js 下载的源文件。
使用 拷贝脚本（推荐） 会报错。
下载源文件后第一次启动成功。后续报错
![20241029-143633](https://github.com/user-attachments/assets/608efb77-5347-40d8-adeb-745097c61229)

**Comment by StageGuard** [comment]
网络原因无法访问 jsdelivr cdn

**Comment by qiuyueovo** [comment]
> 网络原因无法访问 jsdelivr cdn
那么第二个也是由这个问题引起的吗
![image](https://github.com/user-attachments/assets/5dd3f5c1-7845-4356-80c7-111c1759e9d3)
除开代理的情况下有没有什么方法可以解决呢

**Comment by qiuyueovo** [comment]
或者我直接改代码，改成固定的等于？
