### ISSUE TITLE
翻译

### ISSUE THREAD

**Issue by iamjunioru** [StageGuard/SkyAutoPlayerScript#4]
我想将您的脚本翻译成葡萄牙语，该怎么办？

**Comment by StageGuard** [comment]
抱歉没看到issue，我会在几天内做出语言选择功能，并支持通过仓库文件引用翻译

**Comment by StageGuard** [comment]
Hi!
SkyAutoplayerScript 已经更新版本 21，支持了多语言。
查看 https://github.com/StageGuard/SkyAutoPlayerScript/blob/master/contribute-translation.md 来了解如何翻译成其他语言。
