### ISSUE TITLE
播放框位置修改请求

### ISSUE THREAD

**Issue by TrustAsia** [StageGuard/SkyAutoPlayerScript#5]
请问如何修改播放框位置？ 现在的播放框在我的设备上会挡住琴键 导致无法正常播放

**Comment by StageGuard** [comment]
第一次弹奏时有悬浮提示：
拖动标题栏改变播放面板位置

**Comment by TrustAsia** [comment]
> 第一次弹奏时有悬浮提示：
> 拖动标题栏改变播放面板位置

了解了 抱歉 之前没看到
