### ISSUE TITLE
I haven't been able to use it since tgc released an update on the piano.

### ISSUE THREAD

**Issue by Gritc** [StageGuard/SkyAutoPlayerScript#9]
Every time I use it to play the piano, I can't play any song. For example, if a song has a 3 or 4 note, it will play one note and lose the other. Is there any way to fix it?

**Comment by StageGuard** [comment]
I can't fully understand, could you please describe the detail or record screen?

**Comment by Gritc** [comment]
https://user-images.githubusercontent.com/86697824/123904433-a87eb800-d99a-11eb-811f-03543bd6566a.mp4
I have the same problem as in the video and my device doesn't have High-Performance Mode(60fps).

**Comment by StageGuard** [comment]
That's it. It is low fps that causes the key lost. You need to change another device.Others have also had the same problem before and they solve it by setting graphic quality to High Performance Mode.On Jun 30, 2021 13:05, Gritc ***@***.***> wrote:
https://user-images.githubusercontent.com/86697824/123904433-a87eb800-d99a-11eb-811f-03543bd6566a.mp4
I have the same problem as in the video and my device doesn't have High-Performance Mode(60fps).

**Comment by Gritc** [comment]
I see other apps are subject to change to accommodate Sky's update. Can you edit it to make it compatible?

**Comment by StageGuard** [comment]
Probably not. I think it is a bug instead of a new feature. Playing at low graphic quality works well in early version of Sky. Maybe TGC will fix it in the future.
Currently you can solve it by playing at a relatively low speed(e.g. 0.8x).
